[phases.build]
dependsOn = ["install"]

[phases.install]
dependsOn = ["setup"]

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[start]
cmd = "cd backend && node supabase-server.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"