[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"
SUPABASE_URL = "https://fsohtauqtcftdjcjfdpq.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzb2h0YXVxdGNmdGRqY2pmZHBxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjIyNjc4MCwiZXhwIjoyMDY3ODAyNzgwfQ.vLRzjcMIrpn8m3nEDI7pE7bSZg20Msdw60CHcsV1otI"
JWT_SECRET = "48+94YRopTBl0JnUccUCg39wWz4SoSdIlShys4Ra/P0="
SESSION_SECRET = "p0/oPh81xrlqUPWvQhBor11jMuglDfExOSnRU/yo1ag="
FRONTEND_URL = "${{ RAILWAY_PUBLIC_DOMAIN }}"
CORS_ORIGIN = "${{ RAILWAY_PUBLIC_DOMAIN }}"