[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "npm ci"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"

[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npx serve -s build -l $PORT"

[services.variables]
NODE_ENV = "production"
REACT_APP_API_URL = "${{ backend.RAILWAY_PUBLIC_DOMAIN }}"
