[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"
JWT_SECRET = "zELLhvq1BRfepKM9q3pFrnj4QcJq/87+5/BIK26Juzg="
SESSION_SECRET = "/zhYswCgaVbT8Apfav2SS6vd5fUmOTk03pyKyx0Nc/U="
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
DB_HOST = "${{ Postgres.PGHOST }}"
DB_PORT = "${{ Postgres.PGPORT }}"
DB_DATABASE = "${{ Postgres.PGDATABASE }}"
DB_USER = "${{ Postgres.PGUSER }}"
DB_PASSWORD = "${{ Postgres.PGPASSWORD }}"
REDIS_URL = "${{ Redis.REDIS_URL }}"
DB_SSL = "true"
LOG_LEVEL = "info"
ENABLE_METRICS = "true"
ENABLE_CACHING = "true"
FRONTEND_URL = "${{ RAILWAY_PUBLIC_DOMAIN }}"
CORS_ORIGIN = "${{ RAILWAY_PUBLIC_DOMAIN }}"