apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ai-masterclass
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  JWT_SECRET: Y2hhbmdlX3RoaXNfand0X3NlY3JldA== # change_this_jwt_secret
  SESSION_SECRET: Y2hhbmdlX3RoaXNfc2Vzc2lvbl9zZWNyZXQ= # change_this_session_secret
  DB_PASSWORD: Y2hhbmdlX3RoaXNfcGFzc3dvcmQ= # change_this_password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-masterclass-app
  namespace: ai-masterclass
  labels:
    app: ai-masterclass-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-masterclass-app
  template:
    metadata:
      labels:
        app: ai-masterclass-app
    spec:
      containers:
      - name: app
        image: ai-masterclass:latest
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SESSION_SECRET
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD
        - name: DB_USER
          value: "ai_user_prod"
        envFrom:
        - configMapRef:
            name: ai-masterclass-config
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: app-uploads
          mountPath: /app/uploads
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: app-uploads
        persistentVolumeClaim:
          claimName: app-uploads-pvc
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-uploads-pvc
  namespace: ai-masterclass
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: Service
metadata:
  name: ai-masterclass-service
  namespace: ai-masterclass
  labels:
    app: ai-masterclass-app
spec:
  selector:
    app: ai-masterclass-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-masterclass-ingress
  namespace: ai-masterclass
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.your-domain.com
    secretName: ai-masterclass-tls
  rules:
  - host: api.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-masterclass-service
            port:
              number: 5000