apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-masterclass-config
  namespace: ai-masterclass
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "ai_masterclass_prod"
  REDIS_URL: "redis://redis-service:6379"
  PORT: "5000"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
  ENABLE_CACHING: "true"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "1000"
  AUTH_RATE_LIMIT_MAX: "10"
  REQUEST_TIMEOUT: "30000"
  KEEP_ALIVE_TIMEOUT: "65000"